development: 
  amazon_bucket_name: pyklocal-dev
  amazon_access_key: AKIAIJMNT4ZQTAM5CNKQ
  amazon_access_secret: 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
  s3_host_name: s3-us-west-2.amazonaws.com

production:
  amazon_bucket_name: pyklocal-prod
  amazon_access_key: AKIAIJMNT4ZQTAM5CNKQ
  amazon_access_secret: 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
  s3_host_name: s3-us-west-2.amazonaws.com

staging:
  amazon_bucket_name: pyklocal-staging
  amazon_access_key: AKIAIJMNT4ZQTAM5CNKQ
  amazon_access_secret: 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
  s3_host_name: s3-us-west-2.amazonaws.com