common: &default_settings
  :access_key_id: <%= API_CONFIG['amazon_access_key'] %>
  :secret_access_key: <%= API_CONFIG['amazon_access_secret'] %>
  :bucket: <%= API_CONFIG['amazon_bucket_name'] %>
  :s3_host_name: <%= API_CONFIG['s3_host_name'] %>

production: &production
  
  :images:
    :attachment:
      :storage: !ruby/symbol s3
      :s3_protocol: <%= Rails.env == "production" ? :https : :http %>
      :s3_credentials:
        <<: *default_settings
      :styles:
        :mini: '48x48>'
        :small: '100x100>'
        :product: '240x240>'
        :thumb: '400x400>'
        :large: '600x600>'
      :url: '/spree/products/:id/:style/:basename.:extension'
      :path: '/spree/products/:id/:style/:basename.:extension'
      :default_style: :product
      :default_url: '/assets/missing.png'
      :convert_options:
        :all: '-strip -auto-orient -colorspace sRGB'
  :stores:
    :logo:
      :storage: !ruby/symbol s3
      :s3_protocol: <%= Rails.env == 'production' ? :https : :http %>
      :s3_credentials:
        <<: *default_settings
      :styles:
        :mini: '48x48>'
        :small: '100x100>'
        :large: '240x240>'
development:
  <<: *production
