common: &default_settings
  :access_key_id: <%= API_CONFIG['amazon_access_key'] %>
  :secret_access_key: <%= API_CONFIG['amazon_access_secret'] %>
  :bucket: <%= API_CONFIG['amazon_bucket_name'] %>
  :s3_host_name: <%= API_CONFIG['s3_host_name'] %>

production: &production
  
  :images:
    :attachment:
      :storage: !ruby/symbol s3
      :s3_protocol: <%= Rails.env == "production" ? :https : :http %>
      :s3_credentials:
        <<: *default_settings
      :styles:
        :mini: '48x48>'
        :small: '100x100>'
        :product: '240x240>'
        :thumb: '400x400>'
        :large: '600x600>'
      :url: '/spree/products/:id/:style/:basename.:extension'
      :path: '/spree/products/:id/:style/:basename.:extension'
      :default_style: :product
      :default_url: '/images/pyc-logo.png'
      :convert_options:
        :all: '-strip -auto-orient -colorspace sRGB'
  :stores:
    :logo:
      :storage: !ruby/symbol s3
      :s3_protocol: <%= Rails.env == 'production' ? :https : :http %>
      :s3_credentials:
        <<: *default_settings
      :styles:
        :mini: '48x48>'
        :small: '100x100>'
        :large: '240x240>'
        :logo: '167x137#'
      :url: '/stores/:id/:style/:basename.:extension'
      :path: '/stores/:id/:style/:basename.:extension'
      :default_style: :logo
      :default_url: '/images/pyc-logo.png'
      :convert_options:
        :all: '-strip -auto-orient -colorspace sRGB'
  :carousel_images:
    :image:
      :storage: !ruby/symbol s3
      :s3_protocol: <%= Rails.env == 'production' ? :https : :http %>
      :s3_credentials:
        <<: *default_settings
      :styles:
        :mini: '50x50>'
        :large: '350x350>'
        :banner: '600x300>'
        :thumb: '360x360#'
        :landscape: '1140x750#'
      :url: '/carousel_images/:id/:style/:basename.:extension'
      :path: '/carousel_images/:id/:style/:basename.:extension'
      :default_style: :banner
      :default_url: '/images/pyc-logo.png'
      :convert_options:
        :all: '-strip -auto-orient -colorspace sRGB'
  :info_commercials:
    :videos:
      :storage: !ruby/symbol s3
      :s3_protocol: <%= Rails.env == 'production' ? :https : :http %>
      :s3_credentials:
        <<: *default_settings
      :styles:
        :mp4video:
          :geometry: '520x390'
          :format: 'mp4'
          :convert_option: 
            :output:
              :vcode: 'libx264'
              :vpre: 'ipod640'
              :b: '250k'
              :bt: '50k'
              :acode: 'libfaac'
              :ab: '56k'
              :ac: 2
        :preview:
          :geometry: '300x300>'
          :format: 'jpg'
          :time: 5
      :processors: ['ffmpeg']
      :size: 
        :in: 0..25.megabytes
      :s3_permissions: 'public_read'
      :url: '/info_commercials/:id/:basename.:extension'
      :path: '/info_commercials/:id/:basename.:extension'
development:
  <<: *production

test:
  <<: *production
